# Generated by Django 3.2.16 on 2022-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptomodel',
            name='marketcap',
            field=models.CharField(max_length=120),
        ),
    ]
