# Generated by Django 3.2.16 on 2022-12-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cryptomodel_marketcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptomodel',
            name='marketcap',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
